version: "3.6"
services:
  webapp:
    build: ./server
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - WEBAPP_URL=http://webapp:3000
      - BOT_URL=http://bot:9999/visit
      - FLAG=ptm{Low_effort_flag |ಠ_ಠ|}
      - ADMIN_PWD=f787d517-b295-43c6-899a-0d8035821af7
      - RECAPTCHA_SECRET_KEY=
  bot:
    build: ./bot
    environment:
      - WEBAPP_URL=http://webapp:3000
      - ADMIN_PWD=f787d517-b295-43c6-899a-0d8035821af7
